### ISSUE TITLE
heroku hosted ruby on rails repo

### ISSUE THREAD

**Issue by oalbacha** [brandonschabell/daskeyboard-applet-circleci#3]
How do I set this applet up for heroku hosted ruby on rails repo? Can you please assist?

**Comment by ghost** [comment]
Hello oalbacha,
Check out this article on how to set up a Rails application to be hosted via Heroku.
https://devcenter.heroku.com/articles/getting-started-with-rails5

Happy Coding,
Brandon

**Comment by oalbacha** [comment]
Hi brandon,
The app is already hosted, I am asking how to use the circleci applet on my keyboard for the app and triggering on test fails or success

**Comment by brandonschabell** [comment]
Hi, do you already have CircleCI setup? Is your project on GitHub?

**Comment by oalbacha** [comment]
Yes project is my company's private repo on Github and CircleCI is also setup. I only need to get the keyboard applet working with the repo and CI. I have followed the instructions on the README file of this repo and added my CircleCI personal API key to the das keyboard applet but still doesn't work. Any help is much appreciated

**Comment by brandonschabell** [comment]
Sure, can you describe a little more about which part isn't working? Have you been able to add your GitHub repository in the DasKeyboard applet?

**Comment by oalbacha** [comment]
Well, none of the keys are triggering even when I install the applet  to test. I mean all the set up seems to be done right but the trigger and keys are not working at all

**Comment by brandonschabell** [comment]
Would you be able to show a screenshot of your configuration?

**Comment by oalbacha** [comment]
sorry here you go:

![image](https://user-images.githubusercontent.com/17005317/56278604-9694ff80-6117-11e9-9d39-038b799b7db4.png)

**Comment by oalbacha** [comment]
@brandonschabell any clues as to how I can get this to work on my das keyboard?

**Comment by brandonschabell** [comment]
It looks like your setup is correct. Can you open up your Das Keyboard Q app and navigate to "dashboard" and click on the key you selected to use with the CircleCI applet? Can you send a screenshot that shows the info popup?

**Comment by oalbacha** [comment]
![image](https://user-images.githubusercontent.com/17005317/56639602-1a07a100-6682-11e9-8c80-3209ae2337fb.png)

**Comment by brandonschabell** [comment]
@oalbacha  It appears to be configured correctly. Is the issue that a failing build is not causing it to flash red?

**Comment by oalbacha** [comment]
Never mind. My fault. There quite mode was activated in the preferences and I didn’t see it

**Comment by brandonschabell** [comment]
@oalbacha No problem, I'm glad it's working!
